# .github/workflows/pr-comment-notifier.yml

# 워크플로우의 이름을 지정합니다. GitHub Actions 탭에 이 이름이 표시됩니다.
name: PR Comment Notifier

on:
  issue_comment:
    types: [created]

jobs:
  notify:
    if: github.event.issue.pull_request
    uses: rhsiddlsidhd/central-ops/.github/workflows/on-pr-comment-slack-notify.yml@main
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
